### ISSUE TITLE
Teams kan ikke redigeres fra team-detaljer side

### ISSUE THREAD

**Issue by rannveigskjerve** [navikt/accessibility-reporting-tool-frontend#110]
Eiere av team får ikke mulighet til å redigere team inne på team siden

<img width="1412" alt="Screenshot 2024-08-21 at 12 23 58" src="https://github.com/user-attachments/assets/cd4df568-b95d-466f-b528-d1c6ea1585f8">

**Comment by nima-hakimi** [comment]
@rannveigskjerve its fixed :D
