### ISSUE TITLE
Liten skrivefeil i tekst

### ISSUE THREAD

**Issue by macbruker** [navikt/accessibility-reporting-tool-frontend#160]
Fant en liten skrivefeil i headeren her:
https://github.com/navikt/accessibility-reporting-tool-frontend/blob/4c9863034bc6dcea435a3b2272fe4a52a8286d1e/src/components/navbar/Navbar.astro#L55

Inlogget -> Innlogget

**Comment by nima-hakimi** [comment]
Ah, tusen takk @macbruker  :)
