### ISSUE TITLE
Riktig nivå på Headings

### ISSUE THREAD

**Issue by Amirhlotfi** [navikt/accessibility-reporting-tool-frontend#35]
Jeg ser at dere bruker mye fra designsystemet, kjempe bra!

Merk at Heading fra Aksel er default H1.  Bruk `level` propen til å endre til H2, H3 ...
https://aksel.nav.no/komponenter/core/typography#headingdemo-level

Heading-nivåer skal heller ikke skippes
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#usage_notes

**Comment by Matstn** [comment]
Tror dette skal være i orden nå
