### ISSUE TITLE
fix-dynamic-routing-to-report-from-teams-page

### ISSUE THREAD

**Issue by Matstn** [navikt/accessibility-reporting-tool-frontend#81]
Hvis man går inn på et team fra "Teams"-siden, så kan man ikke komme seg til rapportsiden for en bestemt rapport i lista til teamet. Det er fordi URL'en blir "https://a11y-statement-ny.ansatt.dev.nav.no/team/reports/{id}". "team" skal ikke være i den URL'en.

**Comment by nima-hakimi** [comment]
Er denne løst @Matstn
